# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7c42da92-5364-41d0-900d-68c9410d94e3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7c42da92-5364-41d0-900d-68c9410d94e3" = {
     device = "/dev/disk/by-uuid/7c42da92-5364-41d0-900d-68c9410d94e3";
     crypttabExtraOpts = [ "tpm2-device=auto" ];
  };


boot.initrd.luks.devices."luks-393a2045-5645-4ede-8372-449f43eca944".device = "/dev/disk/by-uuid/393a2045-5645-4ede-8372-449f43eca944";
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E81D-8DF8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-393a2045-5645-4ede-8372-449f43eca944"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
